import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import beers from "../data/beers";
import Beer from "../components/beer";

export const getStaticProps = async () => {
  return {
    props: {
      beers,
    },
  };
};

export default function Home(props) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Taplist - Chairlift Brewing Co.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://use.typekit.net/hdm6ujk.css" />
      </Head>
      <header className={styles.header}>
        <Image
          src="/images/chairlift-logo.svg"
          height={90}
          width={243}
          alt="Chairlift brewing co. logo"
        />
      </header>
      {props.beers.length != 0
        ? props.beers.map((beerInfo) => (
            <Beer {...beerInfo} key={beerInfo.tap} />
          ))
        : "NO BEERS! Time to brew, maaaaaaan."}
    </div>
  );
}
